2020-10-05 19:56:50,253 ERROR __main__ Error parsing in process_fresh()


Traceback (most recent call last):
  File "./main.py", line 158, in <module>
    process_fresh(fresh_posts)
  File "./main.py", line 134, in process_fresh
    raise Exception("Error parsing in process_fresh()")
Exception: Error parsing in process_fresh()
2020-10-05 19:57:15,886 ERROR __main__ Error parsing in process_fresh()


Traceback (most recent call last):
  File "./main.py", line 158, in <module>
    process_fresh(fresh_posts)
  File "./main.py", line 134, in process_fresh
    raise Exception("Error parsing in process_fresh()")
Exception: Error parsing in process_fresh()
